[pytest]
DJANGO_SETTINGS_MODULE = smartdorm.settings
python_files = tests.py test_*.py *_tests.py
env =
    PYTEST_DB_HOST=postgres
    PYTEST_DB_PORT=5432
    PYTEST_DB_USER=pg
    PYTEST_DB_PASSWORD=${DB_PASSWORD}
    PYTEST_DB_NAME=testing_pytest
    POSTGRES_DB=testing_pytest