include		/etc/openldap/schema/core.schema
include		/etc/openldap/schema/cosine.schema
include		/etc/openldap/schema/inetorgperson.schema

pidfile		/run/openldap/slapd.pid
argsfile	/run/openldap/slapd.args

modulepath /usr/lib/openldap
moduleload back_mdb.so

database	mdb
maxsize		1073741824
suffix		"dc=schollheim,dc=net"
rootdn		"cn=admin,dc=schollheim,dc=net"
rootpw		demo_ldap_admin
directory	/var/lib/openldap/openldap-data
index	objectClass	eq