"""
Builds the SEPA direct debit file (pain.008) the Finanzenreferat submits to the bank.

The point of generating it here rather than exporting a spreadsheet is that two details are
easy to get wrong by hand and expensive when wrong:

  - the sequence type. The first collection under a mandate must be FRST, every later one
    RCUR. A wrong sequence type comes back as a rejected collection days later.
  - the mandate signature date, which the bank matches against the mandate itself.

Both are tracked on Membership and filled in from there.
"""

import logging
import re
from decimal import Decimal

from sepaxml import SepaDD

from .. import config as app_config
from . import crypto_utils

logger = logging.getLogger(__name__)

# Schema the bank expects. pain.008.001.02 is the long-standing German default and needs a
# creditor BIC; pain.008.001.08 is the newer variant where the BIC is optional.
PAIN_SCHEMA = 'pain.008.001.02'

# SEPA restricts references to this character set. Anything else is rejected on submission.
SEPA_SAFE = re.compile(r"[^A-Za-z0-9/\-?:().,'+ ]")


class SepaConfigError(RuntimeError):
    """Raised when the Verein's own creditor data is not configured yet."""


def sanitize_reference(value, max_length=35):
    """Reduce a string to the SEPA-permitted character set and length."""
    cleaned = SEPA_SAFE.sub('', (value or '').strip())
    return cleaned[:max_length]


def build_mandate_reference(tenant_id, join_date):
    """
    Mandate reference for a new membership: HSV-<Jahr>-<Bewohner-ID, 5-stellig>.

    Unique per creditor (which is what SEPA requires), stable, and traceable back to a
    person without having to look anything up. Uniqueness is additionally enforced by the
    unique constraint on Membership.mandate_reference.
    """
    return sanitize_reference(f"HSV-{join_date.year}-{tenant_id:05d}")


def check_creditor_config():
    """
    Verify the Verein's creditor identity is filled in.

    Called before a collection file is built so the failure is a clear message to the
    Finanzenreferat rather than a file the bank silently rejects.
    """
    missing = []
    if not app_config.HSV_CREDITOR_ID or app_config.HSV_CREDITOR_ID.startswith('DE00ZZZ'):
        missing.append('Gläubiger-Identifikationsnummer (HSV_CREDITOR_ID)')
    if not app_config.HSV_CREDITOR_IBAN:
        missing.append('IBAN des Vereinskontos (HSV_CREDITOR_IBAN)')
    if PAIN_SCHEMA == 'pain.008.001.02' and not app_config.HSV_CREDITOR_BIC:
        missing.append('BIC des Vereinskontos (HSV_CREDITOR_BIC)')

    if missing:
        raise SepaConfigError(
            "Die Gläubigerdaten des Vereins sind noch nicht hinterlegt: "
            + ', '.join(missing)
            + ". Siehe docs/membership_legal.md."
        )


def build_end_to_end_id(membership, collection_date):
    """Per-transaction reference that shows up on the member's bank statement."""
    return sanitize_reference(
        f"HSV-{collection_date.strftime('%Y%m')}-{membership.tenant_id:05d}"
    )


def build_direct_debit_xml(memberships, collection_date, amount):
    """
    Build the pain.008 document.

    `memberships` must already be filtered to collectable members - see
    Membership.is_collectable. Each entry's IBAN is decrypted here, at the last possible
    moment, and never leaves this function.

    Returns (xml, items, message_id). The MsgId is generated by sepaxml inside the header
    before we get a chance to set it, so it is read back out rather than imposed - the
    caller stores it so a later question from the bank can be tied to a run.
    """
    check_creditor_config()

    config = {
        'name': app_config.HSV_CREDITOR_NAME,
        'IBAN': crypto_utils.normalize_iban(app_config.HSV_CREDITOR_IBAN),
        'batch': True,
        'creditor_id': app_config.HSV_CREDITOR_ID,
        'currency': 'EUR',
        'instrument': 'CORE',
    }
    if app_config.HSV_CREDITOR_BIC:
        config['BIC'] = app_config.HSV_CREDITOR_BIC

    sepa = SepaDD(config, schema=PAIN_SCHEMA, clean=True)

    amount_cents = int((Decimal(amount) * 100).to_integral_value())
    items = []

    for membership in memberships:
        payment = {
            'name': membership.account_holder or membership.tenant.get_full_name(),
            'IBAN': membership.get_iban(),
            'amount': amount_cents,
            'type': membership.sequence_type,
            'collection_date': collection_date,
            'mandate_id': membership.mandate_reference,
            'mandate_date': membership.mandate_signed_on,
            'description': f"Mitgliedsbeitrag HSV e.V. {collection_date.strftime('%m/%Y')}",
            'endtoend_id': build_end_to_end_id(membership, collection_date),
        }
        sepa.add_payment(payment)
        items.append({
            'membership': membership,
            'mandate_reference': membership.mandate_reference,
            'sequence_type': membership.sequence_type,
            'amount': Decimal(amount),
            'end_to_end_id': payment['endtoend_id'],
        })

    xml_bytes = sepa.export(validate=True)
    return xml_bytes.decode('utf-8'), items, sepa.msg_id
