# Generated by Django 4.1 on 2024-12-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_claim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('points', models.DecimalField(decimal_places=2, max_digits=19)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 't_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentSignature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('department_name', models.CharField(max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('signed_on', models.DateField()),
            ],
            options={
                'db_table': 't_department_signature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('compensate', models.BooleanField()),
                ('external_id', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=19)),
                ('semester', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_engagement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementApplication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=255)),
                ('motivation', models.TextField()),
                ('external_id', models.CharField(max_length=255)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_engagement_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfflineUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('permissions', models.IntegerField()),
            ],
            options={
                'db_table': 'offline_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfflineUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('permissions', models.TextField()),
            ],
            options={
                'db_table': 'offline_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrived', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('external_id', models.CharField(max_length=255)),
                ('picked_up', models.DateTimeField(blank=True, null=True)),
                ('registered', models.BooleanField()),
            ],
            options={
                'db_table': 't_parcel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('move_in', models.DateField()),
                ('moved_out', models.DateField()),
            ],
            options={
                'db_table': 't_rental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('house', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('type', models.CharField(max_length=255)),
                ('post_row', models.IntegerField()),
            ],
            options={
                'db_table': 't_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtenant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateField()),
                ('external_id', models.CharField(max_length=255)),
                ('move_in', models.DateField()),
                ('move_out', models.DateField()),
                ('university_confirmation', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_subtenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('current_floor', models.CharField(blank=True, max_length=255, null=True)),
                ('current_points', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('current_room', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('email', models.CharField(max_length=255)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('move_in', models.DateField()),
                ('move_out', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('probation_end', models.DateField()),
                ('study_field', models.CharField(max_length=255)),
                ('sublet', models.FloatField(blank=True, null=True)),
                ('surname', models.CharField(max_length=255)),
                ('tel_number', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('new_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='smartdorm.tenant')),
                ('created_on', models.DateField()),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_departure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepositBank',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='smartdorm.tenant')),
                ('name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_deposit_bank',
                'managed': False,
            },
        ),
    ]
