# Generated by Django 4.1 on 2025-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAppSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_semester', models.CharField(default='WS24/25', help_text='Current academic semester (e.g., WS24/25, SS25)', max_length=50)),
                ('applications_open', models.BooleanField(default=False, help_text='Are new applications currently being accepted?')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to settings.')),
            ],
            options={
                'verbose_name': 'Global App Setting',
                'verbose_name_plural': 'Global App Settings',
                'db_table': 't_global_app_settings',
            },
        ),
    ]
