# Generated by Django 4.1 on 2025-05-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0002_globalappsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalappsettings',
            name='current_semester',
            field=models.CharField(default='SS25', help_text='Current academic semester (e.g., WS24/25, SS25)', max_length=50),
        ),
    ]
