# Generated by Django 4.2.21 on 2025-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0003_alter_globalappsettings_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalappsettings',
            name='show_applications',
            field=models.BooleanField(default=False, help_text='Are engagement applications for the next semester visible to all tenants?'),
        ),
    ]
