# Generated by Django 4.2.21 on 2025-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0004_globalappsettings_show_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalappsettings',
            name='show_applications',
            field=models.BooleanField(default=False, help_text='Are engagement applications visible to tenants?'),
        ),
    ]
