# Generated by Django 4.2.21 on 2025-12-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0005_alter_globalappsettings_show_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='termination_record', serialize=False, to='smartdorm.tenant')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_termination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DepartmentExtension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('months', models.IntegerField(help_text='Number of months to extend (positive) or reduce (negative)')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='department_extensions', to='smartdorm.tenant')),
            ],
            options={
                'db_table': 't_department_extension',
                'managed': True,
            },
        ),
    ]
