# Generated by Django 4.2.21 on 2025-12-15 20:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import smartdorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0005_alter_globalappsettings_show_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name des Druckers (z.B. Samsung Xpress C1860FW)', max_length=255)),
                ('location', models.CharField(help_text='Standort (z.B. Kreativreferat Zimmer)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Global ein/aus')),
                ('allow_new_sessions', models.BooleanField(default=True, help_text='Neue Sessions erlauben')),
                ('price_per_page', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Preis pro Seite in Euro', max_digits=5)),
                ('max_session_duration_minutes', models.IntegerField(default=30, help_text='Maximale Session-Dauer in Minuten')),
                ('cups_printer_name', models.CharField(help_text='Name des Druckers in CUPS (z.B. Samsung_C1860_Series)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Verantwortliches Referat', on_delete=django.db.models.deletion.PROTECT, to='smartdorm.department')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 't_device',
            },
        ),
        migrations.CreateModel(
            name='PrintSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('COMPLETED', 'Abgeschlossen'), ('EXPIRED', 'Abgelaufen'), ('TERMINATED', 'Beendet')], default='ACTIVE', max_length=20)),
                ('external_id', models.CharField(default=smartdorm.models.generate_external_id, max_length=255, unique=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.device')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.tenant')),
            ],
            options={
                'verbose_name': 'Print Session',
                'verbose_name_plural': 'Print Sessions',
                'db_table': 't_print_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Relativer Pfad zu temporärem Storage (scans/temp/session_XXX/...)', max_length=500)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(default=smartdorm.models.generate_external_id, max_length=255, unique=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.device')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.printsession')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.tenant')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'db_table': 't_scan',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('pages', models.IntegerField(blank=True, help_text='Anzahl gedruckter Seiten (wird nach Druck aktualisiert)', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Kosten in Euro (nur bei COMPLETED)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Wartend'), ('PRINTING', 'Druckt'), ('COMPLETED', 'Erfolgreich'), ('FAILED', 'Fehlgeschlagen'), ('CANCELLED', 'Abgebrochen')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cups_job_id', models.CharField(blank=True, help_text='CUPS Job ID für Status-Abfrage', max_length=255, null=True)),
                ('external_id', models.CharField(default=smartdorm.models.generate_external_id, max_length=255, unique=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.device')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.printsession')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.tenant')),
            ],
            options={
                'verbose_name': 'Print Job',
                'verbose_name_plural': 'Print Jobs',
                'db_table': 't_print_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
