# Generated by Django 4.2.21 on 2025-08-17 21:13
#Migration to make the engagemetn application table indexed to allow for a page where engagement applications can be viewed

from django.db import migrations

CREATE_ENGAGEMENT_APP_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS t_engagement_application_semester_dep_ten_idx
ON t_engagement_application (semester, department_id, tenant_id);
"""

DROP_ENGAGEMENT_APP_INDEX_SQL = """
DROP INDEX IF EXISTS t_engagement_application_semester_dep_ten_idx;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0005_alter_globalappsettings_show_applications'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_ENGAGEMENT_APP_INDEX_SQL,
            reverse_sql=DROP_ENGAGEMENT_APP_INDEX_SQL,
        ),
    ]