# Generated by Django 4.2.21 on 2025-11-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0005_alter_globalappsettings_show_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BUDGET', 'Budgetantrag'), ('REIMBURSEMENT', 'Rückerstattung')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt'), ('PAID', 'Bezahlt')], default='OPEN', max_length=20)),
                ('requester_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(max_length=34)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_within_budget', models.BooleanField(default=False)),
                ('receipt_file', models.BinaryField(blank=True, null=True)),
                ('receipt_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='smartdorm.department')),
                ('tenant', models.ForeignKey(db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartdorm.tenant')),
            ],
            options={
                'db_table': 't_budget_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BudgetVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('APPROVE', 'Zustimmen'), ('REJECT', 'Ablehnen')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='smartdorm.budgetrequest')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdorm.user')),
            ],
            options={
                'db_table': 't_budget_vote',
                'managed': True,
                'unique_together': {('request', 'voter')},
            },
        ),
    ]
