# Generated by Django 4.2.21 on 2025-12-17 20:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0006_device_printsession_scan_printjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='allow_new_sessions',
            field=models.BooleanField(default=True, help_text='Allow new sessions'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cups_printer_name',
            field=models.CharField(help_text='Name of the printer in CUPS (e.g. Samsung_C1860_Series)', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(help_text='Responsible department', on_delete=django.db.models.deletion.PROTECT, to='smartdorm.department'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global on/off'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(help_text='Location (e.g. Creative Department Room)', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='max_session_duration_minutes',
            field=models.IntegerField(default=30, help_text='Maximum session duration in minutes'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Name of the printer (e.g. Samsung Xpress C1860FW)', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_per_page',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Price per page in Euro', max_digits=5),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost in Euro (only for COMPLETED)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='cups_job_id',
            field=models.CharField(blank=True, help_text='CUPS Job ID for status query', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Number of printed pages (updated after printing)', null=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRINTING', 'Printing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='file_path',
            field=models.CharField(help_text='Relative path to temporary storage (scans/temp/session_XXX/...)', max_length=500),
        ),
    ]
