# Generated by Django 4.2.21 on 2026-04-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0006_termination_departmentextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parts_count', models.IntegerField(default=1, help_text='How many parts one attendance tracking session can have')),
                ('required_parts', models.IntegerField(default=1, help_text='How many parts are required to count as attended')),
                ('admin_groups', models.JSONField(default=list, help_text="List of LDAP groups that can manage this event. 'ADMIN' always has permission.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='CREATED', max_length=20)),
                ('current_part', models.IntegerField(default=0, help_text='The currently active part (1 to parts_count). 0 means none active.')),
                ('secret_token', models.CharField(blank=True, max_length=64, null=True)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='smartdorm.event')),
            ],
            options={
                'db_table': 't_attendance_session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.IntegerField(help_text='Which part of the session (e.g., 1, 2, 3) this record applies to')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='smartdorm.attendancesession')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='smartdorm.tenant')),
            ],
            options={
                'db_table': 't_attendance_record',
                'managed': True,
                'unique_together': {('tenant', 'session', 'part')},
            },
        ),
    ]
