# Generated by Django 4.2.21 on 2025-12-18 21:15

from decimal import Decimal
from django.db import migrations, models


def migrate_price_data(apps, schema_editor):
    """Migrate existing price_per_page to price_per_page_color and set price_per_page_gray"""
    Device = apps.get_model('smartdorm', 'Device')
    for device in Device.objects.all():
        # If device has old price_per_page (via raw SQL), use it for color, otherwise use default
        # Since we're adding fields first, we can't directly access price_per_page
        # So we'll use defaults which is fine for new installs
        pass  # Default values are set in AddField operations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0007_alter_device_allow_new_sessions_and_more'),
    ]

    operations = [
        # First add new fields with defaults
        migrations.AddField(
            model_name='device',
            name='price_per_page_color',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Price per color page in Euro', max_digits=5),
        ),
        migrations.AddField(
            model_name='device',
            name='price_per_page_gray',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Price per black & white page in Euro', max_digits=5),
        ),
        migrations.AddField(
            model_name='printjob',
            name='color_mode',
            field=models.CharField(choices=[('Color', 'Color'), ('Gray', 'Gray')], default='Color', help_text='Color mode used for this job', max_length=10),
        ),
        # Then remove old field (Django will handle this automatically)
        migrations.RemoveField(
            model_name='device',
            name='price_per_page',
        ),
    ]
