# Generated by Django 4.2.21 on 2026-04-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0008_attendancesession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parts_count', models.IntegerField(help_text='Number of parts to count as attended')),
                ('note', models.TextField(blank=True, help_text='Reason for adding base attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_attendance_records', to='smartdorm.event')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='base_attendance_records', to='smartdorm.tenant')),
            ],
            options={
                'db_table': 't_base_attendance_record',
                'managed': True,
                'unique_together': {('tenant', 'event')},
            },
        ),
    ]
