# Generated by Django 4.2.21 on 2026-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0008_add_color_gray_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this job was settled/paid by administration. NULL = still outstanding.', null=True),
        ),
    ]
