# Generated by Django 4.2.21 on 2026-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartdorm", "0009_printjob_settled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IP address or hostname of the Raspberry Pi running CUPS and the scan service (e.g. 10.50.0.15). Falls back to CUPS_SERVER setting when empty.",
                max_length=255,
            ),
        ),
    ]
