# Generated by Django 4.2.21 on 2026-04-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0009_baseattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='previous_secret_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
