# Generated by Django 4.2.21 on 2026-05-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartdorm", "0010_attendancesession_previous_secret_token"),
        ("smartdorm", "0010_device_ip_address"),
    ]

    operations = []
