# Generated by Django 4.2.21 on 2026-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartdorm", "0011_merge_20260519_0814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseattendancerecord",
            name="parts_count",
            field=models.IntegerField(
                help_text="Number of sessions attended in the old system (stored as 'parts_count' for database compatibility)"
            ),
        ),
    ]
