# Generated by Django 4.2.21 on 2026-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartdorm", "0012_alter_baseattendancerecord_parts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="copies",
            field=models.IntegerField(
                default=1,
                help_text="Number of copies requested (needed by the Pi agent to print)",
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Uploaded PDF to be fetched and printed by the Pi agent.",
                null=True,
                upload_to="print_jobs/",
            ),
        ),
        migrations.AddField(
            model_name="printsession",
            name="pending_scan",
            field=models.JSONField(
                blank=True,
                help_text="Set when a scan is requested; the Pi agent reads it, scans, uploads, then it is cleared. Example: {'resolution': 300, 'mode': 'Color', 'source': 'Flatbed'}",
                null=True,
            ),
        ),
    ]
