# Generated by Django 4.2.21 on 2026-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0013_printjob_copies_printjob_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapRoleAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='LDAP cn of the account', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text="Snapshot of the account's display name, for the overview list", max_length=255, null=True)),
                ('group_dn', models.CharField(help_text='Full DN of the granted LDAP group', max_length=512)),
                ('note', models.TextField(blank=True, help_text='Why this role was granted', null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Last day the role is valid. Empty means unlimited.', null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_ldap_role_assignment',
                'managed': True,
                'unique_together': {('username', 'group_dn')},
            },
        ),
    ]
