# Generated by Django 4.2.21 on 2026-09-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0014_ldaproleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOnboarding',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding', serialize=False, to='smartdorm.tenant')),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_step', models.IntegerField(default=0, help_text='Zuletzt gesehener Schritt der Tour')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboardings',
                'db_table': 't_tenant_onboarding',
                'managed': True,
            },
        ),
    ]
