# Generated by Django 4.2.21 on 2026-08-31 22:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import smartdorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdorm', '0014_ldaproleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(help_text='MsgId der pain.008, eindeutig gegenüber der Bank', max_length=35, unique=True)),
                ('collection_date', models.DateField(help_text='Fälligkeitsdatum des Einzugs')),
                ('amount_per_member', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('xml', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_direct_debit_run',
                'ordering': ['-collection_date', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipPrompt',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membership_prompt', serialize=False, to='smartdorm.tenant')),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_membership_prompt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Eingereicht'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt')], default='SUBMITTED', max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('requested_join_date', models.DateField(help_text='Gewünschtes Beitrittsdatum')),
                ('is_of_age', models.BooleanField(help_text='Selbstauskunft: mindestens 18 Jahre alt')),
                ('amtsliste_consent', models.BooleanField(default=False)),
                ('statutes_accepted', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('SEPA', 'SEPA-Lastschriftmandat'), ('OTHER', 'Andere Zahlungsmethode (mit dem Finanzenreferat vereinbart)')], default='SEPA', max_length=10)),
                ('account_holder_first_name', models.CharField(blank=True, max_length=255)),
                ('account_holder_last_name', models.CharField(blank=True, max_length=255)),
                ('iban_ciphertext', models.TextField(blank=True)),
                ('iban_last4', models.CharField(blank=True, max_length=4)),
                ('mandate_confirmed', models.BooleanField(default=False, help_text='Mandat erteilt und Berechtigung zur Erteilung bestätigt')),
                ('terms_version', models.CharField(help_text='Version des Erklärungstextes, der beim Absenden angezeigt wurde', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_by_username', models.CharField(max_length=255)),
                ('declaration_pdf', models.BinaryField(blank=True, help_text='Gerendertes PDF der Erklärung. In der DB statt im Dateisystem, weil es die IBAN enthält und MEDIA_ROOT vom Webserver ausgeliefert werden kann.', null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('decision_note', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='smartdorm.tenant')),
            ],
            options={
                'db_table': 't_membership_application',
                'ordering': ['-submitted_at'],
                'managed': True,
            },
            bases=(smartdorm.models.EncryptedIbanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membership', serialize=False, to='smartdorm.tenant')),
                ('joined_on', models.DateField(help_text='Beitrittsdatum')),
                ('ended_on', models.DateField(blank=True, help_text='Ende der Mitgliedschaft. Endet laut Beitrittserklärung automatisch mit dem Mietverhältnis.', null=True)),
                ('amtsliste_consent', models.BooleanField(default=False)),
                ('amtsliste_consent_at', models.DateTimeField(blank=True, null=True)),
                ('mandate_reference', models.CharField(blank=True, help_text='Mandatsnummer. Eindeutig pro Gläubiger, max. 35 Zeichen.', max_length=35, null=True, unique=True)),
                ('mandate_signed_on', models.DateField(blank=True, help_text='Datum der Mandatserteilung - geht so in die pain.008 ein.', null=True)),
                ('mandate_status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('REVOKED', 'Widerrufen'), ('EXPIRED', 'Abgelaufen'), ('NONE', 'Kein Mandat (andere Zahlungsmethode)')], default='NONE', max_length=10)),
                ('payment_method', models.CharField(choices=[('SEPA', 'SEPA-Lastschriftmandat'), ('OTHER', 'Andere Zahlungsmethode (mit dem Finanzenreferat vereinbart)')], default='SEPA', max_length=10)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('iban_ciphertext', models.TextField(blank=True)),
                ('iban_last4', models.CharField(blank=True, max_length=4)),
                ('last_collection_on', models.DateField(blank=True, help_text='Letzter Einzug. Entscheidet über FRST/RCUR und über den Ablauf des Mandats nach 36 Monaten ohne Nutzung.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='smartdorm.membershipapplication')),
            ],
            options={
                'db_table': 't_membership',
                'ordering': ['-joined_on'],
                'managed': True,
            },
            bases=(smartdorm.models.EncryptedIbanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectDebitItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mandate_reference', models.CharField(max_length=35)),
                ('sequence_type', models.CharField(help_text='FRST oder RCUR', max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('membership', models.ForeignKey(db_column='membership_tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='debit_items', to='smartdorm.membership')),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smartdorm.directdebitrun')),
            ],
            options={
                'db_table': 't_direct_debit_item',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='membershipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('tenant',), name='uniq_open_membership_application'),
        ),
        migrations.AlterUniqueTogether(
            name='directdebititem',
            unique_together={('run', 'membership')},
        ),
    ]
